config/routes.rb
Visor::Application.routes.draw do
  get "reviews/show"
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  # Redirect root for now
  # get "/" => redirect("/reviews/google-nexus-5")
  get "/" => 'home#index'

  # Robots.txt
  get '/robots.txt' => 'home#robots'

  # Reviews
  resources :reviews, only: [:show]

  # QuestionForm
  resources :question_forms, only: [:create]
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  def show
    @review = Content::Review.fuzzy_find(params[:id])
    @product = @review.product
    @sidebar_gallery = @product.gallery('right_sidebar_1', true)
    @related = @product.related_products
    @question_form = QuestionForm.new
    @search_products = @product.related_products(4)
  end
end

app/helpers/reviews_helper.rb
module ReviewsHelper

  def group_scores(product)
    @product.group_scores.sort_by { |s| s.name }
  end

  def show_gallery?(gallery)
    gallery.count > 0
  end
end

app/views/reviews/_email_riddler.erb
<script type="text/javascript">
/*<![CDATA[*/

/***********************************************
* Encrypt Email script- Please keep notice intact
* Tool URL: http://www.dynamicdrive.com/emailriddler/
* **********************************************/
<!-- Encrypted version of: dev [at] *****.** //-->

var emailriddlerarray=[100,101,118,64,118,105,115,111,114,46,105,111]
var encryptedemail_id57='' //variable to contain encrypted email
for (var i=0; i<emailriddlerarray.length; i++)
 encryptedemail_id57+=String.fromCharCode(emailriddlerarray[i])

document.write('<a href="mailto:'+encryptedemail_id57+'?subject=Hello Visor">Email</a>')

/*]]>*/
</script>

app/views/reviews/_related.html.erb
<h2 class="vsr-Review-section-title">Other products like this</h2>

<ul class="vsr-ProductList vsr-ProductList--related">
  <% related.each do |product| %>
    <li class="vsr-ProductList-item">
      <%= link_to review_path(product.review), class: "vsr-ProductList-item-thumb", title: product.full_name do %>
          <img class="u-imgResponsive" src="<%= product.vanity.image.thumb('x100').url %>" alt="<%= product.vanity.description %>">
      <% end %>

      <%= link_to(review_path(product.review), html_options = {class: "vsr-ProductList-item-score", title: "Score"}) do %>
        <%= product.display_score_value %>
      <% end %>

      <%= link_to product.brand_name, review_path(product.review), class: "vsr-ProductList-item-brand" %>
      <%= link_to product.name, review_path(product.review), class: "vsr-ProductList-item-title" %>
      <%= link_to(review_path(product.review), html_options = {class: "vsr-ProductList-item-price"}) do %>
        <span class="vsr-ProductList-item-price-label">Price:</span> <%= product_price(product) %>
      <% end %>
    </li>
  <% end %>
</ul>

app/views/reviews/_search_product_list.html.erb
<ul class="vsr-Search-results Grid Grid--withGutter">
  <% products.each do |product| %>
    <li class="Grid-cell u-size1of4">
      <a class="vsr-Search-result" href="#">
        <img class="vsr-Search-result-thumb u-alignMiddle u-pullLeft" src="<%= product.vanity.image.thumb('75x75#').url %>" alt="">
        <span class="vsr-Search-result-vendor"><%= product.brand_name %></span><span class="vsr-Search-result-model"><%= product.name %></span>
      </a>
    </li>
  <% end %>
</ul>

app/views/reviews/_sidebar_gallery.html.erb
<% if show_gallery?(gallery) %>
  <div class="slider vsr-Cell" id="sliderProduct">
    <ul class="slides">
      <% gallery.each do |item| %>
        <li class="slide slide--white">
          <img src="<%= item.image.thumb('343x343').url %>" alt="<%= item.description %>">
        </li>
      <% end %>
    </ul>
  </div>
  <!-- .slider -->
<% end %>

app/views/reviews/_vertical_graph.html.erb
<li class="vsr-Chart-item">
  <div class="vsr-Chart-value vsr-Chart-value--horizontal">
    <span class="valueData" data-value="<%= score.display_score_value %>"></span>
  </div>
  <!--  .vsr-Chart-Value -->
  <p class="vsr-Chart-label"><%= score.name %>: <span class="vsr-Chart-label vsr-Chart-label--score"><%= score.display_score_value %>/100</span></p>
</li>

app/views/reviews/show.html.erb
<div class="container container--padding">
    <div class="vsr-Review">

        <!-- REVIEW INTRO -->
        <div class="row half">
            <div class="7u">
                <div class="vsr-ReviewIntro">
                    <h1>
                        <span class="vsr-ReviewIntro-brand"><%= @product.brand_name %></span>
                        <span class="vsr-ReviewIntro-title"><%= @review.title %></span>
                    </h1>
                    <h2 class="vsr-ReviewIntro-author"><i class="fa fa-pencil"></i> <a href="#about-popup" class="open-popup-link">Visor Ai</a> on November 20, 2013 <span class="vsr-ReviewIntro-author-links"><i class="fa fa-envelope"></i> <%= render 'email_riddler' %> <i class="fa fa-twitter"></i> <a href="http://twitter.com/visorapp">@visorapp</a></span></h2>
                    <div id="about-popup" class="popup mfp-hide">
                        <h1 class="popup-title">What is Visor?</h1>

                        <p class="popup-info">Visor is a intelligent little being that creates living product reviews that change over time with the life of the product.</p>

                        <p class="popup-info">Its reviews always stay up to date based on how the product currently performs against others in the market.</p>
                    </div>
                    <!-- #aboutPopup -->
                </div>
                <!--  .vsr-ReviewIntro -->
            </div><!-- .7u -->
            <div class="5u">
                <ul class="vsr-ReviewMeta">
                    <li class="vsr-ReviewMeta-item">
                        <a href="<%= @product.amazon_link %>" data-track="true" data-category="Clickthrough" data-action="Amazon" data-location="product-title-bar-1">
                            <img src="<%= @product.vanity.image.thumb('x100').url %>" alt="<%= @product.vanity.description %>">
                        </a>
                    </li>
                    <li class="vsr-ReviewMeta-item">
                        <canvas id="review_meta_score" class="review-meta-score" width="80" height="80" data-value="<%= @product.display_score_value %>"></canvas>
                        <p class="vsr-ReviewMeta-label u-supportColor"><span class="vsr-ReviewMeta-score"><%= @product.display_score_value %></span></p>
                    </li>
                    <li class="vsr-ReviewMeta-item">
                        <a class="vsr-Review-buyOptions-price" href="<%= @product.amazon_link %>" data-track="true" data-category="Clickthrough" data-action="Amazon" data-location="where-to-buy-2"><%= product_price(@product) %> <span class="vsr-Review-buyOptions-meta">+ tax &amp; shipping</span></a>
                    </li>
                    <li class="vsr-ReviewMeta-item">
                        <a href="<%= @product.amazon_link %>" class="Button Button--secondary Button--centered" data-track="true" data-category="Clickthrough" data-action="Amazon" data-location="where-to-buy-3">Buy Now <i class="fa fa-check"></i></a>
                    </li>
                </ul>
            </div>
            <!--  .5u -->
        </div>
        <!--  .row half -->

        <!-- REVIEW BODY -->
        <div class="row half">
            <div class="12u">
                <div class="vsr-Review-body">
                    <%= @review.content.html_safe %>
                </div>
                <!--  .vsrReview-body -->
            </div>
            <!--  .12u -->
        </div>
        <!--  .row half -->

        <div class="row half">
            <!-- WHERE TO BUY -->
            <div class="7u">
                <div class="vsr-Review-buyOptions">
                    <h2 class="vsr-Review-section-title">How much does it cost</h2>

                        <a class="vsr-Review-buyOptions-price u-pullLeft" href="<%= @product.amazon_link %>" data-track="true" data-category="Clickthrough" data-action="Amazon" data-location="where-to-buy-2"><%= product_price(@product) %> <span class="vsr-Review-buyOptions-meta">+ tax &amp; shipping</span></a>

                        <a href="<%= @product.amazon_link %>" class="Button u-pullRight" data-track="true" data-category="Clickthrough" data-action="Amazon" data-location="where-to-buy-3">Buy Now <i class="fa fa-check"></i></a>

                </div>
                <!--  .vsr-Review-buyOptions -->
            </div>

            <!-- SHARE -->
            <!--  .7u -->
            <div class="5u">
                <div class="vsr-Review-share">
                    <h3 class="vsr-Review-section-title">Tell your friends</h3>
                    <ul class="socialcount vsr-Social" data-url="<%= request.original_url %>">
                        <li class="facebook"><a href="https://www.facebook.com/sharer/sharer.php?u=<%= request.original_url %>" title="Share on Facebook" data-track="true" data-category="Share" data-action="Facebook" data-location="review-side-content-1"><i class="fa fa-facebook"></i><span class="count">Like</span></a></li>

                        <li class="twitter"><a href="https://twitter.com/intent/tweet?text=<%= request.original_url %>" title="Share on Twitter" data-track="true" data-category="Share" data-action="Twitter" data-location="review-side-content-1"><i class="fa fa-twitter"></i><span class="count">Tweet</span></a></li>

                        <li class="googleplus"><a href="https://plus.google.com/share?url=<%= request.original_url %>" title="Share on Google Plus" data-track="true" data-category="Share" data-action="Google Plus" data-location="review-side-content-1"><i class="fa fa-google-plus"></i><span class="count">+1</span></a></li>

                        <li class="emailshare">
                            <a href="mailto:?subject=<%= @review.title %> on Visor.io&body=Check out the <%= @review.title %> on Visor.io. You can find it here: <%= request.original_url %>" data-track="true" data-category="Share" data-action="Email Sahre" data-location="review-side-content-1">
                               <i class="fa fa-envelope"></i><span class="count">Email</span>
                            </a>
                        </li>
                    </ul>
                </div>
                <!--  .vsr-Review-share -->
            </div>
            <!--  .5u -->
        </div>
        <!--  .row half -->

        <div class="row half">
            <!-- REVIEW SCORES -->
            <div class="7u">
                <div class="vsr-Review-scores">
                    <h2 class="vsr-Review-section-title">How does it score</h2>
                    <ul class="vsr-Chart vsr-Chart--bar">

                      <% group_scores(@product).each do |score| %>
                        <%= render 'vertical_graph', score: score %>
                      <% end %>

                    </ul>
                    <!--  .vsr-Review-Score-Chart -->
                </div>
                <!--  .vsr-Review-scores -->
            </div>
            <!--  .7u -->

            <!-- RELATED PRODUCTS -->
            <div class="5u">
                <div class="vsr-RelatedProducts">
                    <%= render 'related', related: @related %>
                </div>
                <!--  .vsr-RelatedProducts -->
            </div>
            <!--  .5u -->
        </div>
        <!--  .row half -->

    </div>
    <!--  .Review -->
</div>
<!--  .container container-padding -->